<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>DualScreenWallpaper</AssemblyName>
    <Version>2.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DualScreenWallpaper.Core/DualScreenWallpaper.Core.csproj" />
    <ProjectReference Include="../DualScreenWallpaper.Windows/DualScreenWallpaper.Windows.csproj" />
  </ItemGroup>
</Project>
